PACKAGE_NAME="sb-ae9"
PACKAGE_VERSION="0.1.0"
AUTOINSTALL="yes"
BUILT_MODULE_NAME[0]="snd-hda-core"
BUILT_MODULE_LOCATION[0]="driver/hda-core"
DEST_MODULE_LOCATION[0]="/updates"
BUILT_MODULE_NAME[1]="snd-hda-codec-ca0132"
BUILT_MODULE_LOCATION[1]="driver/ca0132"
DEST_MODULE_LOCATION[1]="/updates"
MAKE[0]="make -C driver/hda-core KDIR=/lib/modules/${kernelver}/build && make -C driver/ca0132 KDIR=/lib/modules/${kernelver}/build"
CLEAN="make -C driver/hda-core clean; make -C driver/ca0132 clean"
